### ISSUE TITLE
No support for recursive structures

### ISSUE THREAD

**Issue by jjfeiler** [invopop/jsonschema#11]
The project I am working on includes structures that are a subset of json-schema itself. That is, a struct that can include an array or map of references to its own type. 

With the following structs:

type Flat struct {
	String string
	Array []string
}

type Recursive struct {
	String string
	Array []*Recursive
}

Flat encodes fine, but Recursive results in a stack overflow.

A more complicated example of a struct that won't encode is the jsonschema.Schema struct itself, since it includes the following field

	AllOf []*Schema `json:"allOf,omitempty"` // section 10.2.1.1

There doesn't seem to be a way to capture the fact that types may need references to IDs before the schemmas are fully generted.

**Comment by samlown** [comment]
I set up a test around #13 and sure enough, it crashes. You can get around this by using the test I defined there, specifically, these lines and new Schema ID lookup capabilities: https://github.com/invopop/jsonschema/pull/13/files#diff-885219898ce44e1ef342ea0fbb3a37b92c59ad12e63d07a9f2c7163517679f82R373-R381 (There is another bug there with the root ID, fixed by #12 and pending release.)

It should be relatively easy to fix however without needing to define a lookup method, we just need to ensure the root is properly registered. If you were to embed the Recursive structure first in another structure, it should work. I'll have a look shortly though.

**Comment by samlown** [comment]
Okay, so that was actually quite easy. Should be fixed in #13 if you'd like to checkout that branch (`go get github.com/invopop/jsonschema@recursive`).

**Comment by jjfeiler** [comment]
I pulled in https://github.com/invopop/jsonschema/pull/13 and it seems to be working. Didn't even have a chance to commit anything to the fork I'd created to take a swag at fixing it.
